import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

// Credit: portions of this page generated by ChatGPT
// Prompt: "i want to add a simple page where the user can click to upload a resume.
// where would i do that"
// Date: 11/07/2025

function UploadPage() {
    const [resume, setResume] = useState<File | null>(null)

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setResume(e.target.files?.[0] || null)
    }

    const handleUpload = () => {
        if (resume) {
            alert(`Uploaded: ${resume.name}`)
        // TODO: send to backend or cloud storage
        } else {
            alert('Please select a file first.')
        }
    }

    const navigate = useNavigate()

    const handleCancel = () => {
        setResume(null)
        navigate('/')
    }

    return (
        <div>
            <h1>Upload Your Resume</h1>
            <input type="file" accept=".pdf,.doc,.docx" onChange = {handleFileChange}/>
            <button onClick={handleUpload}>Upload</button>
            <button onClick={handleCancel}>Cancel</button>
            {resume && <p>Selected file: {resume.name}</p>}
        </div>
    )
}

export default UploadPage


